/*
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.antennaesdk.messageserver.ws;


import com.github.antennaesdk.common.messages.ServerMessage;
import com.github.antennaesdk.server.messages.ClientMessageWrapper;

/**
 * <code>IClientHandler</code> handles the client messages.
 *
 * Clients from real-world connect to "/client" end-point.
 * All traffic from real-world clients is managed by <code>IClientHandler</code>
 *
 * <ol>
 *     <li>receives messages from clients (mobile/iot/etc) </li>
 *     <li>sends messages to clients </li>
 * </ol>
 */
public interface IClientHandler {

    /**
     * received from clients to be processed by the broker or to be processed in the server-side.
     * @param serverMessage
     */
    public void receiveFromClient( ServerMessage serverMessage);

    /**
     * Message is generated by server-side and to be received by the client.
     */
    public void sendToClient( ClientMessageWrapper clientMessage);
}
