package com.github.antennaesdk.messageserver.ws;


import com.github.antennaesdk.common.messages.ServerMessage;
import com.github.antennaesdk.server.messages.ClientMessageWrapper;

/**
 * <code>IClientHandler</code> handles the client messages.
 *
 * Clients from real-world connect to "/client" end-point.
 * All traffic from real-world clients is managed by <code>IClientHandler</code>
 *
 * <ol>
 *     <li>receives messages from clients (mobile/iot/etc) </li>
 *     <li>sends messages to clients </li>
 * </ol>
 */
public interface IClientHandler {

    /**
     * received from clients to be processed by the broker or to be processed in the server-side.
     * @param serverMessage
     */
    public void receiveFromClient( ServerMessage serverMessage);

    /**
     * Message is generated by server-side and to be received by the client.
     */
    public void sendToClient( ClientMessageWrapper clientMessage);
}
