/*
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.antennaesdk.messageserver.ws;


import com.github.antennaesdk.common.messages.ServerMessage;
import com.github.antennaesdk.server.messages.ClientMessageWrapper;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

/**
 * <code>IClientHandler</code> handles the client messages.
 *
 * Clients from real-world connect to "/client" end-point.
 * All traffic from real-world clients is managed by <code>IClientHandler</code>
 *
 * The clients are free to send any payload to the "/client" end-point.
 * However, the <code>IClientHandler</code> processes only the messages that it understands.
 * All incoming messages are handled by @see {@link ClientTextWebSocketHandler#handleTextMessage(WebSocketSession, TextMessage)}
 *
 * These methods are used within the messaging-server to interact with the listener.
 *
 * <ol>
 *     <li>sends messages to clients </li>
 * </ol>
 */
public interface IClientHandler {

    /**
     * Message is generated by server-side and to be received by the client.
     */
    public void sendToClient( ClientMessageWrapper clientMessage);
}
